name: reDocs Español

on:
  push:
    branches:
      - main # Cambia "main" al nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        run: npx vercel #--token ${{ secrets.VERCEL_TOKEN }} # Reemplaza con tu comando de despliegue
